### PR TITLE
fix: use metav1.Object instead of runtime.Object for more ergonomic annotation handling

### LINKED ISSUE #99: `pkg/controllers/util/annotation/annotation.go` should use `metav1.Object` instead of `pkgruntime.Object` for more ergonomic annotation handling
`k8s.io/apimachinery/pkg/runtime.Object` does not have `GetAnnotations` and `SetAnnotations` methods. As a result the annotation util functions in `pkg/controllers/util/annotation/annotation.go` resort to calling `meta.Accessor(obj)` to convert the object. But `meta.Accessor(obj)` returns an error that must be propagated upwards.

In fact, all current usages of the annotation util functions pass in objects that implement `metav1.Object` interface, which allows calling `SetAnnotations` and `GetAnnotations` without returning errors.

### PR DESCRIPTION
**Pull request by kevin1689-cloud**
related to #99

### CODE REVIEW

File: pkg/controllers/util/annotation/annotation.go [hunk 1]
```diff
@@ -67,7 +58,7 @@ func HasAnnotationKeyValue(obj runtime.Object, key, value string) (bool, error)
 // AddAnnotation adds the given annotation key and value to the given objects ObjectMeta,
 // and overwrites the annotation value if it already exists.
 // Returns true if the object was updated.
-func AddAnnotation(obj runtime.Object, key, value string) (bool, error) {
+func AddAnnotation(obj metav1.Object, key, value string) (bool, error) {
```
Comment (gary-lgy) [inline pkg/controllers/util/annotation/annotation.go:61]: Besides avoiding the `meta.Accessor` overhead, another point of this refactor is to allow calling `AddAnnotation` without having to handle the returned error (given the current code paths, the old implementation of `AddAnnotation` would never return an error anyway).

The following is a possible implementation of `AddAnnotation` that satisfies the requirements:

```golang
func AddAnnotation(obj metav1.Object, key, value string) (bool) {
	has := HasAnnotationKeyValue(obj, key, value)
	if has {
		return false
	}
	annotations := obj.GetAnnotations()
	if annotations == nil {
		annotations = make(map[string]string)
	}
	annotations[key] = value
	obj.SetAnnotations(annotations)
	return true
}
```

Naturally, since the return signature has changed, all the call sites need to be changed (which is a good thing because the old error handling code is merely unnecessary bloat).

**Review by gary-lgy — CHANGES_REQUESTED** [review]
Pls see the above comment.

**Comment by kevin1689-cloud** [comment]
> Pls see the above comment.

Got it, thanks for the example which is very clear. I will working on that.

**Comment by gary-lgy** [comment]
> l



> > Pls see the above comment.
> 
> Got it, thanks for the example which is very clear. I will working on that.

Meanwhile, we're in the process of a major refactor (https://github.com/kubewharf/kubeadmiral/tree/refactor/unified-federated-type) and the code on the main branch will be changed significantly by next week. I suggest delaying this fix until the refactor is done, otherwise we will have to do a lot of rebasing. :)

**Comment by kevin1689-cloud** [comment]
> > > Pls see the above comment.
> > 
> > 
> > Got it, thanks for the example which is very clear. I will working on that.
> 
> Meanwhile, we're in the process of a major refactor (https://github.com/kubewharf/kubeadmiral/tree/refactor/unified-federated-type) and the code on the main branch will be changed significantly by next week. I suggest delaying this fix until the refactor is done, otherwise we will have to do a lot of rebasing. :)

Got it, how about in this pull request we only avoiding the `meta.Accessor` overhead which only need change two files:

- pkg/controllers/util/annotation/annotation.go
- pkg/controllers/util/annotation/annotation_test.go

The refactor which allow calling `AddAnnotation` without having to handle the returned error, we delaying it until the major refactor is done. After the major refactor is done, I can create another pull request to remove the returned error of `AddAnnotation` and change all the call sites.

**Comment by gary-lgy** [comment]
> > > > Pls see the above comment.
> > > 
> > > 
> > > Got it, thanks for the example which is very clear. I will working on that.
> > 
> > 
> > Meanwhile, we're in the process of a major refactor ([`refactor`/unified-federated-type](https://github.com/kubewharf/kubeadmiral/tree/refactor/unified-federated-type?rgh-link-date=2023-07-11T04%3A24%3A55Z)) and the code on the main branch will be changed significantly by next week. I suggest delaying this fix until the refactor is done, otherwise we will have to do a lot of rebasing. :)
> 
> Got it, how about in this pull request we only avoiding the `meta.Accessor` overhead which only need change two files:
> 
> * pkg/controllers/util/annotation/annotation.go
> * pkg/controllers/util/annotation/annotation_test.go
> 
> For the refactor which allow calling `AddAnnotation` without having to handle the returned error, we delaying it until the major refactor is done. After the major refactor is done, I can create another pull request to remove the returned error of `AddAnnotation` and change all the call sites.
> 
> I think by this way we can make some improvement(avoiding the `meta.Accessor` overhead) and minimize the rebasing work. What do you think about that? Thanks!

Sounds good. Please fix the compile error and then LGTM.

**Review by gary-lgy — APPROVED** [review]

**Comment by gary-lgy** [comment]
@kevin1689-cloud thanks!
